spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testDb
    username: pg
    password: pg
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE